services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    networks:
      - proxy-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This allows accessing host machine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

networks:
  proxy-network:
    name: proxy-network
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
